# Generated by Django 4.0.6 on 2022-07-28 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_alter_biglotto_blue_one_alter_biglotto_blue_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglotto',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='twocolorball',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
